AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Check the expiry date of your HTTPS certificates in your VPC. 
Resources:
  sslcheckvpc:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: python3.7
      CodeUri: ./lambda
      Description: ''
      MemorySize: 3008
      Timeout: 120
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          subnet: 172.31.0.0/16
      Tracing: Active
      ReservedConcurrentExecutions: 1
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      Layers: 
        - !Ref LibLayer

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: OpenSSLandIP
      Description: Dependencies for OpenSSL, sslyze and ipaddress.
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete
