AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Check the expiry date of your HTTPS certificates in your VPC. 

Resources:

  sslcheckvpc:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: python3.7
      CodeUri: lambda-scan/
      Description: ''
      MemorySize: 3008
      Timeout: 60
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          subnet: 172.31.37.0/24
      Tracing: Active
      ReservedConcurrentExecutions: 1
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      Layers: 
        - !Ref LibLayer

  configlambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: python3.7
      CodeUri: lambda-config/
      Description: ''
      MemorySize: 128
      Timeout: 10

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PyOpenSSL-IPaddress-sslyze
      Description: Dependencies for OpenSSL, sslyze and ipaddress.
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: ''
      RetentionPolicy: Delete
